spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdsucrimereport
    username: RootDoc
    password: RootDoc45!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # the url, username, and password are all based on your MySQL setup.
  # Here I am using a local hosted connection with my own username and password.

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  mvc:
    async:
      request-timeout: 3600000

server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
